### PR TITLE
Optimise bootstrap usage

### PR DESCRIPTION
**Pull request by noplanman**
Update the layout system to make better use of the bootstrap framework.
Also use bootstrap components for sidebar navigation.

Open to all input!

Here some screenshots.
simple
map
edit-pod

### CODE REVIEW

**Comment by dmorley** [comment]
Looks really nice. I have found that most systems show the scroll bar nice and pretty like that, but my windows machine shows the big win95 scroll bar and it can really mess things up. Just an FYI I had to make some adjustments to make it look ok on win7 before, take a look if you have a VM :(

**Comment by noplanman** [comment]
Ok, will check with Windows too :+1:

Also have an XP VM lying around somewhere 😸

**Comment by noplanman** [comment]
Looks good for me on Windows 7 and XP (using Firefox, on IE6 it's totally broken).

Could you add a screenshot of what it looks like for you?

**Comment by noplanman** [comment]
Issues on Windows XP (just for the record, I don't think this actually matters, right?):
- Can't scroll tables horizontally
- Some Emojis don't exist and they become a placeholder
missing-emojis

**Comment by dmorley** [comment]
Admittedly I looked at it in windows yesterday it looked like your screen shots, In Ubunutu it's not perfect.

It does un-stack the menu for me and put them side by side, I guess that is part of being super responsive? It's good, but it does change view to view and that is weird

The header name remains broken in alpha 6 on FF and Chrome

Agree XP is not "modern" and we should stick to modern to support or deal with insanity.
screenshot from 2017-02-12 06-36-35

screenshot from 2017-02-12 06-06-42

**Comment by dmorley** [comment]
I clearly commented before coffee and should have run bower first :(

**Comment by dmorley** [comment]
From my FF and Chrome. I like how FF displays without the scroll bar at all. Chrome puts the thin one on there.

screenshot from 2017-02-12 07-07-24
screenshot from 2017-02-12 07-06-47

**Comment by dmorley** [comment]
Agree who cares about XP. My thought is anything below a 420 is not worth spending time on https://html5test.com/results/desktop.html

**Comment by dmorley** [comment]
screenshot_20170212-082025
screenshot_20170212-082040
screenshot_20170212-082101

Looks great on mobil also! Not sure if its just my phone but site always freezes up a few seconds on load, even current prod. Yours too?

**Comment by noplanman** [comment]
@dmorley Any more input here?

I'm done for the moment, all pages look nice on my end. 👍

**Comment by noplanman** [comment]
Merged. Time for a freeze and release?

**Comment by dmorley** [comment]
Just pushed one more lil one, then let's freeze and release.

**Pull request merged**
