### PR TITLE
Clean up most of the PHP code.

### PR DESCRIPTION
**Pull request by noplanman**
Big sweep through the PHP code, making it more robust.

### CODE REVIEW

**Comment by dmorley** [comment]
So this seems to be a magical if, then statement very cool. Just trying to understand why only used here and not all if, then statements? Because it is just a simple if this then print that type thing?

$row['service_facebook'] === 't' && print '<div class="smlogo smlogo-facebook"></div>';

**Comment by noplanman** [comment]
What other places are you talking about?

I tend to opt for the simple one-liners for readability, like for the services where there are 5 (almost) identical lines.

**Comment by dmorley** [comment]
But it could be used for something like: 

 if ($_GET['format'] === 'json') {
     echo json_encode($row);
   } else {

if you wanted?

**Comment by noplanman** [comment]
True, but what about the else part?

For some situations, things can be reused and bent, like this for example:
```php
if ($_GET['method'] === 'jsonp') {
  print $_GET['callback'] . '(' . json_encode($obj) . ')';
} else {
  print json_encode($obj);
}
```
would become (using the ternary operator):
```php
$obj_json = json_encode($obj);
echo $_GET['method'] === 'jsonp' ? $_GET['callback'] . '(' . $obj_json . ')' : $obj_json; 
```

But looking at readability, the second is quite difficult to understand.

**Comment by dmorley** [comment]
yea, I am lost looking at that, it's pretty and all, but my brain works better with if, then, do or else type things. I learned Logo then Basic in the 80s, still on that level!

**Comment by noplanman** [comment]
Readability is key!
If it's not readable and understandable, it's bad code, at least to me.

Main thing is for you to understand the code, so if there are any bits that seem weird or illogical, just comment on that line and let me know!

**Pull request merged**
